[package]
name = "sputnik"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.3.0"
rand = "0.8.5"
rand_derive2 = "0.1.17"
strum = "0.24.1"
strum_macros = "0.24.3"
